platform :ios, '9.0'
use_frameworks!

target 'HotCocoa' do

pod 'Alamofire', '~> 3.4'
pod 'AlamofireImage', '~> 2.0'
pod ‘SwiftyJSON’
pod 'SVProgressHUD'
pod 'Segmentio', '~> 1.0'
pod 'UITableViewCell-Badge'
pod 'UIScrollView-InfiniteScroll'
pod 'RAMReel'
pod 'FoldingCell'
pod 'StatefulViewController', '~> 1.0'
pod 'TCTitleLoading'
pod 'XHAmazingLoading'

end