platform :ios, '9.0'
use_frameworks!

target 'HotCocoa' do

pod 'Alamofire', '~> 3.4'
pod 'AlamofireImage', '~> 2.0'
pod ‘SwiftyJSON’
pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
pod 'Segmentio', '~> 1.0'
pod 'UIScrollView-InfiniteScroll'
pod 'RAMReel'
pod 'FoldingCell'
pod 'TCTitleLoading'
pod 'TLTagsControl', :git => 'https://github.com/mohlman3/TLTagsControl.git'
pod 'FCAlertView'
pod 'CTFeedback'
pod 'Bohr'
pod 'ISMessages'
pod 'Cloudinary'
pod 'Socket.IO-Client-Swift', '~> 7.0.0'
pod 'JSQMessagesViewController'
pod 'SwiftRandom'
pod 'BBBadgeBarButtonItem'
pod 'Fabric'
pod 'Crashlytics'
pod 'Fusuma'
pod 'DZNEmptyDataSet'

end