platform :ios, '9.0'
use_frameworks!

target 'HotCocoa' do

pod 'Alamofire', '~> 3.4'
pod 'AlamofireImage', '~> 2.0'
pod ‘SwiftyJSON’
pod 'SVProgressHUD'
pod 'Segmentio', '~> 1.0'
pod 'UITableViewCell-Badge'
pod ‘DisplaySwitcher’, '~> 0.1.1’
pod 'UIScrollView-InfiniteScroll'
pod 'RAMReel'

end